const wordToEmoji: { [Key: string]: string } = {
  soup: '🍲',
  pizza: '🍕',
  doughnut: '🍩',
  pancakes: '🥞',
  waffles: '🧇',
  lamb: '🥩',
  quiche: '🥧',
  frittata: '🥧',
  taco: '🌮',
  burrito: '🌮',
  wrap: '🌮',
  burger: '🍔',
  potato: '🥔',
  patatas: '🥔',
  'hash brown': '🥔',
  'sag aloo': '🥔',
  foccacia: '🥖',
  focaccia: '🥖',
  vegetable: '🥕',
  broccoli: '🥦',
  cake: '🍰',
  pie: '🥧',
  toast: '🍞',
  spaghetti: '🍝',
  'meat ball': '🍝',
  chicken: '🍗',
  turkey: '🦃',
  risotto: '🍚',
  orzo: '🍚',
  dessert: '🍰',
  bacon: '🥓',
  gammon: '🥓',
  salmon: '🐟',
  cabbage: '🥬',
  egg: '🍳',
  'baked beans': '🥫',
  pea: '🟢',
  bean: '🟢',
  onion: '🧅',
  tomato: '🍅',
  mushroom: '🍄',
  steak: '🥩',
  pudding: '🍮',
  chilli: '🌶️',
  chili: '🌶️',
  beef: '🥩',
  carrot: '🥕',
  sponge: '🍰',
  crespelle: '🥞',
  plaice: '🐟',
  haddock: '🐟',
  fish: '🐟',
  cod: '🐟',
  hake: '🐟',
  tuna: '🍣',
  'chow mein': '🍜',
  pasty: '🥟',
  wellington: '🥟',
  'spring roll': '🥟',
  samosa: '🥟',
  fries: '🍟',
  chips: '🍟',
  corn: '🌽',
  aubergine: '🍆',
  parmigiana: '🍆',
  bbq: '🍖',
  ribs: '🍖',
  ragout: '🥘',
  stew: '🥘',
  ratatouille: '🥘',
  crumble: '🥣',
  sausage: '🌭',
  custard: '🍮',
  curry: '🍛',
  tikka: '🍛',
  pork: '🥩',
  scampi: '🐟',
  rice: '🍚',
  pilau: '🍚',
  chocolate: '🍫',
  cheese: '🧀',
  apple: '🍏',
  mango: '🥭',
  'stir fry': '🍲',
  paella: '🍲',
  gnocchi: '🍝',
  pasta: '🍝',
  tortellini: '🍝',
  french: '🇫🇷',
  cauliflower: '🥦',
  courgette: '🥕',
  lasagne: '🍝',
  lasagna: '🍝',
  feast: '🥘',
  flatbread: '🥖',
  garlic: '🧄',
  vegetarian: '🥕',
  'no meal': '😔',
}

export default wordToEmoji
